name: Run News Script and Send Webhook

on:
  schedule:
    - cron: '0 21 * * *'  # الساعة 9 مساءً (بتوقيت UTC)
    - cron: '0 7 * * *'   # الساعة 7 صباحًا (بتوقيت UTC)
  push:
    branches:
      - main

jobs:
  send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install googletrans==1.1.9
          from googletrans_new import googletrans
      - name: Check Python Version and Installed Packages
        run: |
          python --version
          pip freeze

      - name: Run script
        run: python news.py
        continue-on-error: true  # سيستمر في حال حدوث خطأ
