name: News Scraper

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC
    - cron: '0 21 * * *'  # 9 PM UTC

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run News Scraper Script
        run: |
          python news_scraper.py
